// One catalog for the default offline gate. Existing script paths remain valid
// while their application ownership is explicit here.
export const suites = [
  {
    id: "panel-ui",
    label: "Shared Panel App controls",
    commands: [["--test", "tests/panel-select-ui.test.mjs"]],
  },
  {
    id: "packages",
    label: "Package rules and existing application regressions",
    commands: [["scripts/validate.mjs"]],
  },
  {
    id: "build",
    label: "Source packaging, determinism and installation closure",
    commands: [["--test", "tests/panel-build.test.mjs"]],
  },
  {
    id: "design-studio",
    label: "Design Studio project recovery",
    commands: [["--test", "tests/apps/design-studio/portable-backup.test.mjs", "tests/apps/design-studio/recovery-session.test.mjs", "tests/apps/design-studio/recovery-ui.test.mjs"]],
  },
  {
    id: "quant-lab",
    label: "Quant Lab data, portfolio and market workflows",
    commands: [["scripts/test-quant-lab.mjs"]],
  },
  {
    id: "video-download",
    label: "Video Download queue, verified library and AI search",
    commands: [
      [
        "--test",
        ...[
          "cookie-runtime",
          "download-library",
          "download-task",
          "durable-downloads",
          "library-native",
          "package",
          "library-process",
          "project-storage",
          "queue-ui",
          "library-ui",
          "search-source",
          "video-search",
        ].map((name) => `tests/apps/video-download/${name}.test.mjs`),
      ],
    ],
  },
  {
    id: "video-studio",
    label: "Video Studio project model and Host contracts",
    commands: [
      [
        "scripts/run-typescript-tests.mjs",
        "tests/video-studio-voice-library-bridge.test.ts",
        "tests/video-studio-media-task-bridge.test.ts",
        "tests/video-studio-media-file-storage.test.ts",
        "tests/video-studio-external-media.test.ts",
        "tests/video-studio-timeline-menu.test.ts",
        "tests/video-studio-rough-cut-ai.test.ts",
        "tests/video-studio-folder-scan.test.ts",
        "tests/video-studio-folder-source.test.ts",
        "tests/video-studio-folder-import.test.ts",
        "tests/video-studio-folder-files.test.ts",
        "apps/video-studio/native/tests/audio8.test.ts",
        "apps/video-studio/native/tests/qwen.test.ts",
        "apps/video-studio/native/tests/audio-probe.test.ts",
        "tests/video-studio-model.test.ts",
        "tests/video-studio-caption-coverage.test.ts",
        "tests/video-studio-editor-time.test.ts",
        "tests/video-studio-editor-schema.test.ts",
        "tests/video-studio-editor-migration.test.ts",
        "tests/video-studio-export-settings.test.ts",
        "tests/video-studio-editor-operations.test.ts",
        "tests/video-studio-editor-evaluate.test.ts",
        "tests/video-studio-editor-color.test.ts",
        "tests/video-studio-editor-history.test.ts",
        "tests/video-studio-editor-clip-edits.test.ts",
        "tests/video-studio-process-input.test.ts",
        "tests/video-studio-editor-session.test.ts",
        "tests/video-studio-editor-audio.test.ts",
        "tests/video-studio-editor-legacy-adapter.test.ts",
        "tests/video-studio-editor-legacy-reasons.test.ts",
        "tests/video-studio-editor-resource-audio.test.ts",
        "tests/video-studio-editor-task.test.ts",
        "tests/video-studio-editor-timing-edits.test.ts",
        "tests/video-studio-editor-spoken.test.ts",
        "tests/video-studio-editor-rough-cut-placement.test.ts",
        "tests/video-studio-editor-legacy-plan.test.ts",
        "tests/video-studio-editor-import.test.ts",
        "tests/video-studio-editor-export-batch.test.ts",
        "tests/video-studio-editor-agent-tools.test.ts",
        "tests/video-studio-editor-source-previews.test.ts",
        "tests/video-studio-editor-waveform-bridge.test.ts",
        "tests/video-studio-portable-project.test.ts",
        "tests/video-studio-portable-task.test.ts",
        "tests/video-studio-caption-services.test.ts",
        "tests/video-studio-stream-audio.test.ts",
        "tests/video-studio-editor-captions.test.ts",
        "tests/video-studio-editor-sequence-edits.test.ts",
        "tests/video-studio-editor-sync.test.ts",
        "tests/video-studio-editor-multicam.test.ts",
        "tests/video-studio-editor-multicam-bridge.test.ts",
        "tests/video-studio-editor-separation.test.ts",
        "tests/video-studio-editor-audio-enhancement.test.ts",
        "tests/video-studio-editor-voiceover-publication.test.ts",
        "tests/video-studio-editor-markers.test.ts",
        "tests/video-studio-editor-asset-removal.test.ts",
        "tests/video-studio-audio-split.test.ts",
        "tests/video-studio-timeline-controls.test.ts",
        "tests/video-studio-free-timeline.test.ts",
        "tests/video-studio-rough-cut.test.ts",
        "tests/video-studio-rough-cut-controls.test.ts",
        "tests/video-studio-voice-preparation-ui.test.ts",
        "tests/video-studio-host.test.ts",
        "tests/video-studio-production.test.ts",
        "tests/video-studio-production-ui.test.ts",
        "tests/video-studio-production-tools.test.ts",
        "tests/video-studio-tts.test.ts",
        "tests/video-studio-voiceover-publication.test.ts",
        "tests/video-studio-enhancement.test.ts",
        "tests/video-studio-caption-style.test.ts",
        "tests/video-studio-workflow.test.ts",
        "tests/video-studio-narration.test.ts",
        "tests/video-studio-editor-narration.test.ts",
        "tests/video-studio-editor-narration-alignment.test.ts",
      ],
      ["--test", "apps/video-studio/native/tests/voice-runtime.test.mjs"],
    ],
  },
];
